// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpbF9SFf4Zo8hVZk1wdz15iNnuUh_mNro',
    appId: '1:997764759872:web:02f8f6ec743c56dea23aa5',
    messagingSenderId: '997764759872',
    projectId: 'dicedice-943b4',
    authDomain: 'dicedice-943b4.firebaseapp.com',
    storageBucket: 'dicedice-943b4.firebasestorage.app',
    measurementId: 'G-KWQ8Y1SC64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRz6oz27OBujTxOfNq84tu3UdKx9QTVHg',
    appId: '1:997764759872:android:aab7bcf7d2f5510ea23aa5',
    messagingSenderId: '997764759872',
    projectId: 'dicedice-943b4',
    storageBucket: 'dicedice-943b4.firebasestorage.app',
  );
}
